version: "3.8"

volumes:
  postgres_data:

services:

  postgres:
    build:
      context: ./postgres
      target: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=test
    expose:
    - "5432"
    ports:
    - "5432:5432"
    restart: always
    stop_signal: SIGINT
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./postgres/sql/patchdb.d:/docker-entrypoint-patchdb.d

  test:
    build:
      context: .
      target: test
    depends_on:
    - postgres
    environment:
    - CONFIG=/local/test.yaml
    - ENV=/local/docker.env
    volumes:
    - ./assets:/assets
    - ./local:/local

  notifier:
    build:
      context: .
      target: epic.notifier
    depends_on:
    - epic
    - postgres
    environment:
    - CONFIG=/local/notifier.yaml
    - ENV=/local/docker.env
    volumes:
    - ./assets:/assets
    - ./local:/local

  verifier:
    build:
      context: .
      target: epic.verfier
    depends_on:
    - epic
    - postgres
    environment:
    - CONFIG=/local/verifier.yaml
    - ENV=/local/docker.env
    volumes:
    - ./assets:/assets
    - ./local:/local

  epic:
    build:
      context: .
      target: epic.server
    environment:
    - CONFIG=/local/server.yaml
    volumes:
    - ./local:/local
