version: "3.8"

volumes:
  mongo-data:
  postgres-data:

services:
  mongo:
    command: [--noauth, --smallfiles, --quiet]
    expose:
    - "27017"
    image: mongo:4.0.19-xenial
    ports:
    - "27017:27017"
    restart: always
    stop_signal: SIGINT
    volumes:
    - mongo-data:/data/db

  postgres:
    build:
      context: .
      dockerfile: timescaledb.dockerfile
      target: test
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=test
    expose:
    - "5432"
    image: timescaledb
    ports:
    - "5432:5432"
    restart: always
    stop_signal: SIGINT
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./secrets:/secrets:ro
