version: "3.8"

volumes:
  postgres_data:

services:

  postgres:
    build:
      context: ./postgres
      target: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=test
    - TIMESCALEDB_TELEMETRY=off
    - TS_TUNE_MEMORY=8GB
    - TS_TUNE_NUM_CPUS=4
    expose:
    - "5432"
    ports:
    - "5432:5432"
    restart: always
    stop_signal: SIGINT
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./postgres/sql/patchdb.d:/docker-entrypoint-patchdb.d

  test:
    build:
      context: .
      target: test
    environment:
    - CONFIG=./local/test.yaml
    - ENV=./secrets/example.env
    volumes:
    - ./assets:/assets
    - ./gold:/gold
    - ./local:/local
    - ./model:/model
    - ./secrets:/secrets
