version: "3.8"

volumes:
  postgres-data:

services:

  test:
    build:
      context: .
      target: test
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USERNAME=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DATABASE=test
    - POSTGRES_PORT=5432
    volumes:
    - ./sql:/sql

  postgres:
    build:
      context: ./postgres
      target: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=test
    expose:
    - "5432"
    ports:
    - "5432:5432"
    restart: always
    stop_signal: SIGINT
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./postgres/sql:/sql
