[project]
name = "dsdk"
authors = [
    "Michael Becker",
    "Corey Chivers",
    "Jason Lubken"
]
license = "MIT"
python = "^3.7"
readme = "README.rst"

[build-system]
requires = [
    "setuptools>=42.8.0",
    "setuptools_scm[toml]>=3.3.3",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py37","py38"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
exclude_lines = [
    "raise NotImplementedError()",
    "pragma: nocover",
    "if __name__ == .__main__.:",
]
precision = 2
show_missing = true

[tool.coverage.run]
branch = true
source = ["dsdk", "test"]
parallel = true

[tool.isort]
include_trailing_comma = true
line_length = 79
multi_line_output = 3
known_first_party = ["dsdk"]
default_section = "THIRDPARTY"

[tool.pytest.ini_options]
addopts = "-ra --cov=dsdk --cov-report=term-missing --strict --ignore=.eggs --tb=short"
testpaths = ["test"]
norecursedirs = ".env .git .tox build dist"
python_files = "test.py tests.py test_*.py *_test.py"

[tool.setuptools_scm]
