name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4

    - name: test
      run: |
        docker-compose -f docker-compose.test.yml up --exit-code-from test
        docker-compose -f docker-compose.test.yml down
